AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    aws-sap-odp-extractor
    SAM Template for extracting data from SAP applications using Operational Data Provisioning (ODP) and Rest APIs using OData
Globals:
    Function:
        Timeout: 900
Parameters:
    Environment:
        Description: Unique name to add all the resources that are created through this template 
        Type: String
        Default: "saponaws-odp"
    SAPAuthParameterStore:
        Description: Name of the parameter store where SAP Auth information is stored
        Type: String
        Default: "sap-odp-extract-auth"
    S3BucketForData:
        Description: Name of the S3 bucket where the data exract files will be stored
        Type: String
        Default: "sap-odp-data-extracts"    
    DynamoDBTableName:
        Description: Name for the DynamoDB table to store metadata information
        Type: String
        Default: "sap-odp-extract-metadata"

Metadata:
  AWS::ServerlessRepo::Application:
    Name: aws-sap-odp-extractor
    Description: Lambda function for extracting data fromm SAP applications using ODP and OData
    Author: KK Ramamoorthy
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE.txt
    ReadmeUrl: sam-repo/README.md
    Labels: ['saponaws','sap','lambdaextractor','odp']
    HomePageUrl: https://code.amazon.com/packages/Aws-sap-cert-auth/trees/master
    SemanticVersion: 0.0.3
    SourceCodeUrl: https://code.amazon.com/packages/Aws-sap-cert-auth/trees/master

Resources:
    DynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties: 
            AttributeDefinitions: 
                - AttributeName: odpServiceName
                  AttributeType: S
                - AttributeName: odpEntitySetName
                  AttributeType: S
            KeySchema: 
                - AttributeName: odpServiceName
                  KeyType: HASH
                - AttributeName: odpEntitySetName
                  KeyType: RANGE
            ProvisionedThroughput: 
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
            TableName: !Ref DynamoDBTableName

    SAPODPExtractorLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            #LayerName: !Sub ${Environment}-aws-sap-odp-extractor
            LayerName: aws-sap-odp-extractor
            Description: Lamda Layer to extract data fromm SAP applications using ODP and OData
            ContentUri: layers/aws-sap-odp-extractor/
            CompatibleRuntimes:
                - python2.7
                - python3.6
                - python3.7
            LicenseInfo: 'Available under the MIT-0 license.'
            RetentionPolicy: Retain

    SAPODPExtractorTestFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${Environment}-aws-sap-odp-extractor-test
            CodeUri: aws-sap-odp-extractor-test/
            Handler: main.lambda_handler
            Runtime: python3.6
            Policies:
                - DynamoDBCrudPolicy:
                    TableName: !Ref DynamoDBTableName
                - S3CrudPolicy:
                    BucketName: !Ref S3BucketForData
                - SSMParameterReadPolicy:
                    ParameterName: !Ref SAPAuthParameterStore
            Environment:
                Variables:
                    sapHostName:            "<your sap hostname> for e.g. mysaphost.com"
                    sapPort:                "<your sap https port> for e.g. 44300"
                    sapAuthParameterStore:  !Ref SAPAuthParameterStore
                    metaDataDDBName:        !Ref DynamoDBTableName
                    odpServiceName:         "<your odata service name>"
                    odpEntitySetName:       "<your odp entity set name within the odata service>"
                    dataChunkSize:          "1000"
                    dataS3Bucket:           !Ref S3BucketForData
            Layers:
                - !Ref SAPODPExtractorLayer

Outputs:
    SAPUserCertAuthTestFunction:
        Description: "SAP ODP extractor test function ARN"
        Value: !GetAtt SAPODPExtractorTestFunction.Arn
